### PR TITLE
Update nordic-middlename.structuredefinition-extension.xml

### PR DESCRIPTION
**Pull request by jkiddo**
Changed URLs to reflect nordic addressing

### CODE REVIEW

**Review by thomiz — COMMENTED** [review]
Thanks @jkiddo

**Comment by jkiddo** [comment]
I guess this documents the first time we have made a concrete item in collaboration, across borders in the nordic using FHIR ;)

**Comment by rockphotog** [comment]
There will be cake!

**Comment by jkiddo** [comment]
in abundance

**Comment by thomiz** [comment]
Nordic cooperation, check!

**Pull request merged**
